// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath libs.build.gradle
        classpath libs.kotlin.gradle
        classpath libs.navigation.safe.args
        classpath libs.hilt.gradle

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

plugins {
    id "com.github.ben-manes.versions" version "0.42.0"
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

/**
 * Get updated dependency versions
 */
tasks.named("dependencyUpdates").configure {
    checkForGradleUpdate = true
    outputFormatter = { result ->
        def updatable = result.outdated.dependencies
        if (!updatable.isEmpty()){
            def writer = new StringWriter()
            def html = new groovy.xml.MarkupBuilder(writer)

            html.html {
                body {
                    table {
                        thead {
                            tr {
                                td("Group")
                                td("Module")
                                td("Current version")
                                td("Latest version")
                            }
                        }
                        tbody {
                            updatable.each { dependency->
                                tr {
                                    td(dependency.group)
                                    td(dependency.name)
                                    td(dependency.version)
                                    td(dependency.available.release ?: dependency.available.milestone)
                                }
                            }
                        }
                    }
                }
            }
            println writer.toString()
        }
    }
    outputDir = "build/dependencyUpdates"
    reportfileName = "dependency_update_report"
}


task clean(type: Delete) {
    delete rootProject.buildDir
}