[versions]
accompanist = "0.36.0"
androidXTestCoreVersion = "1.6.1"
androidXTestExtKotlinRunnerVersion = "1.2.1"
androidXTestRulesVersion = "1.2.0-beta01"
appCompatVersion = "1.7.0"
archTestingVersion = "2.2.0"
composeActivityVersion = "1.9.2"
composeCompilerVersion = '1.5.4'
composeVersion = '1.7.0'
constraintLayoutVersion = "2.1.4"
coroutinesVersion = "1.8.1"
dataStoreVersion = "1.1.1"
dexMakerVersion = "2.12.1"
espressoVersion = "3.6.1"
googleTruth = "1.4.4"
gradleVersion = "8.6.0"
hamcrestVersion = "1.3"
hiltAndroidXVersion = "1.2.0"
hiltVersion = "2.52"
junitVersion = "4.13.2"
kotlinVersion = "2.0.20"
ktxVersion = "1.13.1"
lifecycleVersion = "2.8.5"
material3WindowSizeClassVersion = "1.3.0"
materialVersion = "1.3.0"
mockitoVersion = "2.25.0"
navigationVersion = "2.8.0"
robolectricVersion = "4.12.1"
roomVersion = "2.6.1"
testExtJunitVersion = "1.2.1"

[libraries]
build-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradleVersion" }
hilt-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltVersion" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinVersion" }
navigation-safe-args = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationVersion" }

accompanist-adaptive = { module = "com.google.accompanist:accompanist-adaptive", version.ref = "accompanist" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompatVersion" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivityVersion"}
compose-androidx = { module = "androidx.compose.ui:ui", version.ref = "composeVersion"}
compose-material = { module = "androidx.compose.material3:material3", version.ref = "materialVersion"}
compose-window-size = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3WindowSizeClassVersion" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigationVersion"}
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeVersion"}
constraint-layout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayoutVersion" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "ktxVersion" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutinesVersion"}
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutinesVersion"}
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStoreVersion"}
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltVersion"}
hilt-library = { module = "com.google.dagger:hilt-android", version.ref = "hiltVersion"}
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltAndroidXVersion"}
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinVersion" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleVersion"}
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleVersion"}
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleVersion" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion"}
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion"}
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion"}

arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "archTestingVersion" }
compose-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeVersion" }
compose-tooling-test = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeVersion" }
dexmaker-mockito = { module = "com.linkedin.dexmaker:dexmaker-mockito", version.ref = "dexMakerVersion" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espressoVersion" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoVersion" }
ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidXTestExtKotlinRunnerVersion" }
google-truth = { module = "com.google.truth:truth", version.ref = "googleTruth" }
hilt-test-android = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltVersion" }
hilt-test-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltVersion" }
junit-base = { module = "junit:junit", version.ref = "junitVersion" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesVersion" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoVersion" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectricVersion" }
test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidXTestCoreVersion" }
test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "testExtJunitVersion" }

[bundles]

[plugins]
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinVersion" }