plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-android-extensions'
    id 'kotlin-kapt'
    id 'dagger.hilt.android.plugin'
    id 'androidx.navigation.safeargs'
}
//`https://sasikanth.dev/posts/gradle-version-catalog`

android {

    compileSdkVersion 30

    defaultConfig {
        applicationId "com.ak.jotit"
        minSdkVersion 22
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        kapt {
            arguments {
                arg("room.schemaLocation", "$projectDir/schemas")
            }
        }
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        viewBinding = true
        compose true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
        freeCompilerArgs += "-Xopt-in=kotlinx.coroutines.ExperimentalCoroutinesApi"
        useIR = true
    }

// this fix is added because of androidTest issues
    packagingOptions {
        exclude 'META-INF/AL2.0'
        exclude 'META-INF/LGPL2.1'
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
    composeOptions {
        kotlinCompilerExtensionVersion libs.versions.composeVersion.get()
    }

}

dependencies {

    implementation libs.kotlin.stdlib
    implementation libs.core.ktx
    implementation libs.appcompat
    implementation libs.google.material
    implementation libs.constraint.layout
    implementation libs.legacy.support.v4

    // Fragment
    implementation libs.fragment.ktx

    // Lifecycle + ViewModel & LiveData
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.lifecycle.livedata.ktx

    // Navigation Component
    implementation libs.navigation.fragment.ktx
    implementation libs.navigation.ui.ktx

    // Room
    implementation libs.room.runtime
    kapt libs.room.compiler
    implementation libs.room.ktx

    // Compose
    implementation libs.compose.androidx
    implementation libs.compose.material
    implementation libs.compose.preview
    implementation libs.lifecycle.runtime.ktx
    implementation libs.compose.activity
    implementation libs.compose.navigation

    // Coroutines
    implementation libs.coroutines.core
    implementation libs.coroutines.android

    // Dagger Hilt
    implementation libs.hilt.library
    implementation libs.hilt.viewmodel
    kapt libs.hilt.compiler

    // DataStore
    implementation libs.datastore.preferences

    // Dependencies for local unit tests
    testImplementation libs.junit.base
    testImplementation libs.google.truth
    androidTestImplementation libs.test.ext.junit
    androidTestImplementation libs.espresso.core
    testImplementation libs.test.core.ktx
    testImplementation libs.robolectric
    testImplementation libs.ext.junit.ktx
    testImplementation libs.arch.core.testing
    testImplementation libs.kotlinx.coroutines.test

    // AndroidX Test . Instrumented testing
    androidTestImplementation libs.test.ext.junit

    // Dependencies for Android instrumented unit tests
    androidTestImplementation libs.junit.base
    androidTestImplementation libs.kotlinx.coroutines.test
    androidTestImplementation libs.mockito.core
    androidTestImplementation libs.dexmaker.mockito
    androidTestImplementation libs.espresso.contrib
    androidTestImplementation libs.arch.core.testing
    androidTestImplementation libs.compose.test
    debugImplementation libs.compose.tooling.test

}