plugins {
    id "com.android.application"
    id "kotlin-android"
    id "kotlin-kapt"
    id "dagger.hilt.android.plugin"
    id "androidx.navigation.safeargs"
}
//`https://sasikanth.dev/posts/gradle-version-catalog`

android {

    compileSdkVersion 33

    defaultConfig {
        applicationId "com.ak.jotit"
        minSdkVersion 22
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "com.ak.jotit.HiltTestRunner"

        kapt {
            arguments {
                arg("room.schemaLocation", "$projectDir/schemas")
            }
        }
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    buildFeatures {
        compose true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
        freeCompilerArgs += "-Xopt-in=kotlinx.coroutines.ExperimentalCoroutinesApi"
        freeCompilerArgs += "-Xopt-in=androidx.compose.foundation.ExperimentalFoundationApi"
        freeCompilerArgs += "-Xopt-in=androidx.compose.material3.ExperimentalMaterial3Api"
        freeCompilerArgs += "-Xopt-in=androidx.compose.ui.ExperimentalComposeUiApi"
    }

// this fix is added because of androidTest issues
    packagingOptions {
        exclude "META-INF/AL2.0"
        exclude "META-INF/LGPL2.1"
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
    composeOptions {
        kotlinCompilerExtensionVersion libs.versions.composeCompilerVersion.get()
    }

}

dependencies {
    implementation project(path: ":core:material2")

    implementation libs.kotlin.stdlib
    implementation libs.core.ktx
    implementation libs.appcompat
    implementation libs.constraint.layout

    // Lifecycle + ViewModel & LiveData
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.lifecycle.livedata.ktx

    // Room
    implementation libs.room.runtime
    kapt libs.room.compiler
    implementation libs.room.ktx

    // Compose
    implementation libs.compose.androidx
    implementation libs.compose.material
    implementation libs.compose.preview
    implementation libs.lifecycle.runtime.ktx
    implementation libs.compose.activity
    implementation libs.compose.navigation

    // Coroutines
    implementation libs.coroutines.core
    implementation libs.coroutines.android

    // Dagger Hilt
    implementation libs.hilt.library
    implementation libs.hilt.navigation
    kapt libs.hilt.compiler

    // DataStore
    implementation libs.datastore.preferences

    // Dependencies for local unit tests
    testImplementation libs.junit.base
    testImplementation libs.google.truth

    // AndroidX Test . Instrumented testing
    androidTestImplementation libs.test.ext.junit

    // Dependencies for Android instrumented unit tests
    androidTestImplementation libs.junit.base
    androidTestImplementation libs.hilt.test.android
    kaptAndroidTest libs.hilt.test.compiler
    androidTestImplementation libs.test.core.ktx
    androidTestImplementation libs.kotlinx.coroutines.test
    androidTestImplementation libs.espresso.contrib
    androidTestImplementation libs.compose.test
    debugImplementation libs.compose.tooling.test

}